"""
Visualization utilities untuk segmentation model analysis.
Includes: Quality distribution plots dan Class Activation Maps (Grad-CAM)
(this file generated by Claude Haiku 4.5)
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.ndimage import gaussian_filter


class ActivationCAM:
    """
    Activation-based CAM untuk U-Net: Extract attention maps dari model.
    Menunjukkan region mana yang penting untuk prediksi model.
    Menggunakan activation maps tanpa backward pass (lebih stabil).
    """
    def __init__(self, model, target_layer):
        """
        Args:
            model: PyTorch model
            target_layer: Layer untuk extract activation (string atau module)
        """
        self.model = model
        self.activations = None
        
        # Register hooks
        if isinstance(target_layer, str):
            target_module = dict([*self.model.named_modules()])[target_layer]
        else:
            target_module = target_layer
            
        target_module.register_forward_hook(self.save_activation)
    
    def save_activation(self, module, input, output):
        self.activations = output.detach()
    
    def generate_cam(self, input_tensor):
        """
        Generate Class Activation Map menggunakan activation strengths.
        
        Args:
            input_tensor: Input image (B, C, H, W)
        
        Returns:
            cam: Attention map (H, W)
        """
        # Forward pass
        with torch.no_grad():
            _ = self.model(input_tensor)
        
        # Compute CAM dari activations
        activations = self.activations[0]  # (C, H, W)
        
        # Weight by channel importance (mean of each channel)
        weights = activations.mean(dim=(1, 2))  # (C,)
        weights = F.softmax(weights, dim=0)
        
        cam = (weights.view(-1, 1, 1) * activations).sum(dim=0)  # (H, W)
        
        # Normalize dan apply ReLU
        cam = F.relu(cam)
        cam = (cam - cam.min()) / (cam.max() - cam.min() + 1e-8)
        
        return cam.cpu().numpy()


def compute_quality_distribution(model, test_loader, device='cuda'):
    """
    Compute Dice dan IoU scores untuk setiap image di dataset.
    
    Args:
        model: U-Net model (already loaded)
        test_loader: DataLoader untuk test/validation set
        device: 'cuda' atau 'cpu'
    
    Returns:
        dict dengan 'dice' dan 'iou' scores per image
    """
    from utils.metrics import SegmentationMetrics
    
    model.eval()
    model.to(device)
    
    dice_scores = []
    iou_scores = []
    metrics_fn = SegmentationMetrics(threshold=0.5)
    
    with torch.no_grad():
        for images, masks in test_loader:
            images = images.to(device)
            masks = masks.to(device)
            
            logits = model(images)
            metrics = metrics_fn.compute(logits, masks)
            
            dice_scores.append(metrics['dice'])
            iou_scores.append(metrics['iou'])
    
    return {
        'dice': dice_scores,
        'iou': iou_scores,
        'mean_dice': np.mean(dice_scores),
        'std_dice': np.std(dice_scores),
        'mean_iou': np.mean(iou_scores),
        'std_iou': np.std(iou_scores),
    }


def plot_quality_distribution(quality_metrics, title="Segmentation Quality Distribution", save_path=None):
    """
    Plot distribusi Dice dan IoU scores.
    
    Args:
        quality_metrics: Output dari compute_quality_distribution()
        title: Judul plot
        save_path: Path untuk save figure (optional)
    """
    fig, axes = plt.subplots(2, 2, figsize=(14, 10), facecolor='white')
    fig.suptitle(title, fontsize=16, fontweight='bold')
    
    # Histogram Dice
    axes[0, 0].hist(quality_metrics['dice'], bins=20, color='skyblue', edgecolor='black', alpha=0.7)
    axes[0, 0].axvline(quality_metrics['mean_dice'], color='red', linestyle='--', linewidth=2.5,
                       label=f"Mean: {quality_metrics['mean_dice']:.3f}")
    axes[0, 0].set_title('Dice Score Distribution', fontweight='bold', fontsize=12)
    axes[0, 0].set_xlabel('Dice Score', fontsize=11)
    axes[0, 0].set_ylabel('Frequency', fontsize=11)
    axes[0, 0].legend(fontsize=10)
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].set_facecolor('white')
    
    # Histogram IoU
    axes[0, 1].hist(quality_metrics['iou'], bins=20, color='lightcoral', edgecolor='black', alpha=0.7)
    axes[0, 1].axvline(quality_metrics['mean_iou'], color='darkred', linestyle='--', linewidth=2.5,
                       label=f"Mean: {quality_metrics['mean_iou']:.3f}")
    axes[0, 1].set_title('IoU Score Distribution', fontweight='bold', fontsize=12)
    axes[0, 1].set_xlabel('IoU Score', fontsize=11)
    axes[0, 1].set_ylabel('Frequency', fontsize=11)
    axes[0, 1].legend(fontsize=10)
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].set_facecolor('white')
    
    # Box plot Dice
    bp1 = axes[1, 0].boxplot(quality_metrics['dice'], vert=True, patch_artist=True)
    for patch in bp1['boxes']:
        patch.set_facecolor('skyblue')
    axes[1, 0].set_title('Dice Score Box Plot', fontweight='bold', fontsize=12)
    axes[1, 0].set_ylabel('Dice Score', fontsize=11)
    axes[1, 0].grid(True, alpha=0.3, axis='y')
    axes[1, 0].set_facecolor('white')
    
    # Box plot IoU
    bp2 = axes[1, 1].boxplot(quality_metrics['iou'], vert=True, patch_artist=True)
    for patch in bp2['boxes']:
        patch.set_facecolor('lightcoral')
    axes[1, 1].set_title('IoU Score Box Plot', fontweight='bold', fontsize=12)
    axes[1, 1].set_ylabel('IoU Score', fontsize=11)
    axes[1, 1].grid(True, alpha=0.3, axis='y')
    axes[1, 1].set_facecolor('white')
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor='white')
        print(f"✓ Quality distribution plot saved to: {save_path}")
    
    plt.show()
    
    # Print statistik
    print(f"\n{'='*50}")
    print(f"SEGMENTATION QUALITY STATISTICS")
    print(f"{'='*50}")
    print(f"Dice Score:")
    print(f"  Mean:     {quality_metrics['mean_dice']:.4f}")
    print(f"  Std Dev:  {quality_metrics['std_dice']:.4f}")
    print(f"  Min:      {np.min(quality_metrics['dice']):.4f}")
    print(f"  Max:      {np.max(quality_metrics['dice']):.4f}")
    print(f"\nIoU Score:")
    print(f"  Mean:     {quality_metrics['mean_iou']:.4f}")
    print(f"  Std Dev:  {quality_metrics['std_iou']:.4f}")
    print(f"  Min:      {np.min(quality_metrics['iou']):.4f}")
    print(f"  Max:      {np.max(quality_metrics['iou']):.4f}")
    print(f"{'='*50}\n")


def visualize_single_cam(model, image, mask=None, target_layer='bottleneck', 
                         device='cuda' if torch.cuda.is_available() else 'cpu'):
    """
    Visualisasi CAM untuk single image.
    
    Args:
        model: U-Net model
        image: Input image (H, W, 3) normalized
        mask: Ground truth mask (H, W), optional
        target_layer: Layer untuk extract CAM
        device: 'cuda' atau 'cpu'
    """
    # Setup
    model.eval()
    model.to(device)
    cam_extractor = ActivationCAM(model, target_layer)
    
    # Prepare input
    if isinstance(image, np.ndarray):
        image_tensor = torch.from_numpy(image).permute(2, 0, 1).unsqueeze(0).float().to(device)
    else:
        image_tensor = image.unsqueeze(0).to(device)
    
    # Generate CAM
    with torch.no_grad():
        cam = cam_extractor.generate_cam(image_tensor)
    
    # Resize CAM ke ukuran original image
    cam_resized = cv2.resize(cam, (image.shape[1], image.shape[0]))
    cam_resized = gaussian_filter(cam_resized, sigma=1.5)  # Smooth
    
    # Prepare plots
    n_plots = 3 if mask is None else 4
    fig, axes = plt.subplots(1, n_plots, figsize=(15, 4), facecolor='white')
    
    # Original image
    if len(image.shape) == 3 and image.shape[2] == 3:
        axes[0].imshow(image)
    else:
        axes[0].imshow(image, cmap='gray')
    axes[0].set_title('Original Image', fontweight='bold')
    axes[0].axis('off')
    
    # CAM heatmap
    im = axes[1].imshow(cam_resized, cmap='jet')
    axes[1].set_title('Grad-CAM (Attention)', fontweight='bold')
    axes[1].axis('off')
    plt.colorbar(im, ax=axes[1], fraction=0.046)
    
    # CAM overlay pada image
    if len(image.shape) == 3 and image.shape[2] == 3:
        overlay = image.copy()
    else:
        overlay = cv2.cvtColor((image * 255).astype(np.uint8), cv2.COLOR_GRAY2RGB) / 255.0
    
    cam_color = cv2.applyColorMap((cam_resized * 255).astype(np.uint8), cv2.COLORMAP_JET)
    cam_color = cv2.cvtColor(cam_color, cv2.COLOR_BGR2RGB) / 255.0
    overlay_blend = 0.6 * overlay + 0.4 * cam_color
    
    axes[2].imshow(overlay_blend)
    axes[2].set_title('Overlay', fontweight='bold')
    axes[2].axis('off')
    
    # Ground truth mask (jika ada)
    if mask is not None:
        axes[3].imshow(mask, cmap='RdYlGn', alpha=0.7)
        axes[3].set_title('Ground Truth Mask', fontweight='bold')
        axes[3].axis('off')
    
    plt.tight_layout()
    plt.show()


def visualize_multiple_cams(model, dataset, num_samples=6, target_layer='bottleneck',
                           device='cuda' if torch.cuda.is_available() else 'cpu', save_path=None):
    """
    Visualisasi CAM untuk multiple samples dari dataset.
    
    Args:
        model: U-Net model
        dataset: ISICDataset instance
        num_samples: Jumlah samples untuk visualisasi
        target_layer: Layer untuk extract CAM
        device: Device untuk inference
        save_path: Path untuk save figure (optional)
    """
    model.eval()
    model.to(device)
    cam_extractor = ActivationCAM(model, target_layer)
    
    # Ambil random samples
    indices = np.random.choice(len(dataset), min(num_samples, len(dataset)), replace=False)
    
    fig, axes = plt.subplots(num_samples, 4, figsize=(16, 4*num_samples), facecolor='white')
    if num_samples == 1:
        axes = axes.reshape(1, -1)
    
    fig.suptitle('Grad-CAM Visualizations', fontsize=16, fontweight='bold')
    
    with torch.no_grad():
        for row, idx in enumerate(indices):
            image, mask = dataset[idx]
            image_np = image.permute(1, 2, 0).numpy()
            mask_np = mask.numpy()
            
            # Generate CAM
            image_tensor = image.unsqueeze(0).to(device)
            cam = cam_extractor.generate_cam(image_tensor)
            
            cam_resized = cv2.resize(cam, (image_np.shape[1], image_np.shape[0]))
            cam_resized = gaussian_filter(cam_resized, sigma=1.5)
            
            # Original
            axes[row, 0].imshow(image_np)
            axes[row, 0].set_title(f'Image {idx}', fontweight='bold', fontsize=10)
            axes[row, 0].axis('off')
            
            # CAM
            im = axes[row, 1].imshow(cam_resized, cmap='jet')
            axes[row, 1].set_title('Grad-CAM', fontweight='bold', fontsize=10)
            axes[row, 1].axis('off')
            
            # Overlay
            overlay = image_np.copy()
            cam_color = cv2.applyColorMap((cam_resized * 255).astype(np.uint8), cv2.COLORMAP_JET)
            cam_color = cv2.cvtColor(cam_color, cv2.COLOR_BGR2RGB) / 255.0
            overlay_blend = 0.6 * overlay + 0.4 * cam_color
            axes[row, 2].imshow(overlay_blend)
            axes[row, 2].set_title('Overlay', fontweight='bold', fontsize=10)
            axes[row, 2].axis('off')
            
            # Ground truth
            axes[row, 3].imshow(mask_np, cmap='RdYlGn', alpha=0.7)
            axes[row, 3].set_title('Ground Truth', fontweight='bold', fontsize=10)
            axes[row, 3].axis('off')
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor='white')
        print(f"✓ CAM visualization saved to: {save_path}")
    
    plt.show()
